adjustment on comment section
ronaldolipata/interactive-comments-section pull request #15
Opened 2023-03-04 03:32 UTC by antonpalermo

I separate some components into their own separate files for us to easily maintain our components @ronaldolipata can you check if this is okay with you?

2023-03-04 03:40 UTC, antonpalermo commented
I also create a comments store so we can easily transition to our data coming from our backend.

2023-03-04 08:04 UTC, ronaldolipata commented
> I separate some components into their own separate files for us to easily maintain our components @ronaldolipata can you check if this is okay with you?

Thanks. @antonpalermo. Looks great!
`nit`: we can also a separate component for the buttons

> I also create a comments store so we can easily transition to our data coming from our backend.

The reducer looks good. We can improve the data fetch from app component in the future.

2023-03-04 08:13 UTC, ronaldolipata requested changes
Hi @antonpalermo, please check my reviews. Thanks

2023-03-04 08:13 UTC, ronaldolipata commented on frontend/src/components/Comment/index.tsx
> +              onEdit={onClickEditHandler}
Remove `onEdit` and `onDelete` from the `CommentAction` props, and move the functions including the store into the CommentActions.

2023-03-04 08:13 UTC, ronaldolipata commented on frontend/src/components/Comment/index.tsx
>          <>
I agree with your comment for `key={id}` should be on the top container of the `comment-container`, and `replies-container`.

2023-03-04 14:51 UTC, antonpalermo commented on frontend/src/components/Comment/index.tsx
> +              onEdit={onClickEditHandler}
I updated the code and removed `onEdit` and `onDelete` in the component props. This is just temporary and we'll update this in the future.

2023-03-04 14:53 UTC, antonpalermo commented on frontend/src/components/Comment/index.tsx
>          <>
Aside from this change, I think we need to update the name for this component. Let's say `Comments` instead of `Comment` since this component renders all comment list.

2023-03-05 07:50 UTC, ronaldolipata commented
Looking great!

2023-03-05 07:51 UTC, merged